FROM mcr.microsoft.com/windows/servercore:10.0.17763.4252@sha256:b90fc3f0259aa56a97616946f6f5d061bd54c3d5c08d2eaff482fd56ab95a6f4

ENV MSYS2_ARG_CONV_EXCL "*"

ENV TMPDIR C:\\Windows\\Temp
ENV TMP C:\\Windows\\Temp
ENV TEMP C:\\Windows\\Temp

COPY ./docker_windows.ps1 /

RUN powershell.exe .\\docker_windows.ps1

RUN del /F/S/Q .\\docker_windows.ps1
