version: 2
updates:

- package-ecosystem: "docker"
  directory: "/docker/linux/ubuntu"
  schedule:
    interval: daily
    time: "06:00"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
