# base
FROM ubuntu:focal as base
ENV LANG en_US.utf8
ENV DEBIAN_FRONTEND=noninteractive


# minimal
FROM base as minimal
ADD ./build_container_common.sh /
ADD ./build_container_ubuntu.sh /
RUN --mount=type=tmpfs,target=/var/cache/apt \
    --mount=type=tmpfs,target=/var/lib/apt/lists \
    ./build_container_ubuntu.sh


# docker
FROM minimal as docker
COPY ./build_container_docker.sh /
RUN --mount=type=tmpfs,target=/var/cache/apt \
    --mount=type=tmpfs,target=/var/lib/apt/lists \
    ./build_container_docker.sh


# llvm
FROM minimal as llvm
ENV LLVM_VERSION=14.0.0
ENV LCOV_VERSION=1.15
COPY ./build_container_llvm.sh /
COPY ./build_container_llvm_ubuntu.sh /
RUN --mount=type=tmpfs,target=/var/cache/apt \
    --mount=type=tmpfs,target=/var/lib/apt/lists \
    ./build_container_llvm_ubuntu.sh


# kitchen-sink
FROM llvm as kitchen-sink
COPY ./build_container_docker.sh /
RUN --mount=type=tmpfs,target=/var/cache/apt \
    --mount=type=tmpfs,target=/var/lib/apt/lists \
    ./build_container_docker.sh
COPY ./build_container_developer.sh /
RUN --mount=type=tmpfs,target=/var/cache/apt \
    --mount=type=tmpfs,target=/var/lib/apt/lists \
    ./build_container_developer.sh
ENV DEBIAN_FRONTEND=


# mobile
FROM kitchen-sink as mobile
ENV ANDROID_SDK_INSTALL_TARGET /.android
ENV ANDROID_HOME /.android/sdk
ENV ANDROID_SDK_ROOT /.android/sdk
ENV ANDROID_NDK_VERSION 21.4.7075529
ENV ANDROID_NDK_HOME /.android/sdk/ndk/21.4.7075529
COPY ./build_container_mobile.sh /
RUN --mount=type=tmpfs,target=/var/cache/apt \
    --mount=type=tmpfs,target=/var/lib/apt/lists \
    ./build_container_mobile.sh


# Make the full image (without Docker) the default
FROM kitchen-sink
