FROM mcr.microsoft.com/windows/servercore:ltsc2022

# @sha256:f1974546e8a73746e6c60781895341dd7a6760e28534d3d0cc5f3c88c1f5825a

ENV MSYS2_ARG_CONV_EXCL "*"

ENV TMPDIR C:\\Windows\\Temp
ENV TMP C:\\Windows\\Temp
ENV TEMP C:\\Windows\\Temp

COPY ./build_container_windows.ps1 /

RUN powershell.exe .\\build_container_windows.ps1

RUN del /F/S/Q .\\build_container_windows.ps1
