#Add qemu function for supporting multiarch
ARG IMAGEARCH
FROM alpine:3.11 as qemu
RUN apk add --no-cache curl
ARG QEMUVERSION=4.0.0
ARG QEMUARCH

SHELL ["/bin/ash", "-o", "pipefail", "-c"]

#RUN curl -fsSL https://github.com/multiarch/qemu-user-static/releases/download/v${QEMUVERSION}/qemu-${QEMUARCH}-static.tar.gz | tar zxvf - -C /usr/bin
#RUN chmod +x /usr/bin/qemu-*

FROM debian:buster-20200908
ARG QEMUARCH

#COPY --from=qemu /usr/bin/qemu-${QEMUARCH}-static /usr/bin/

ADD ./build_container_common.sh /
ADD ./build_container_debian.sh /

RUN ./build_container_debian.sh

# Remove qemu program
#RUN rm -f /usr/bin/qemu-${QEMUARCH}-static
