FROM mcr.microsoft.com/windows/servercore:ltsc2019

ENV MSYS2_ARG_CONV_EXCL "*"

ENV TMPDIR C:\\Windows\\Temp
ENV TMP C:\\Windows\\Temp
ENV TEMP C:\\Windows\\Temp

COPY ./build_container_windows.ps1 /

RUN powershell.exe .\\build_container_windows.ps1

RUN del /F/S/Q .\\build_container_windows.ps1
