#Add qemu function for supporting multiarch
ARG IMAGEARCH
FROM alpine:3.9.2 as qemu
RUN apk add --no-cache curl
ARG QEMUVERSION=4.0.0
ARG QEMUARCH

SHELL ["/bin/ash", "-o", "pipefail", "-c"]

RUN curl -fsSL https://github.com/multiarch/qemu-user-static/releases/download/v${QEMUVERSION}/qemu-${QEMUARCH}-static.tar.gz | tar zxvf - -C /usr/bin
RUN chmod +x /usr/bin/qemu-*

FROM ${IMAGEARCH}ubuntu:bionic
ARG QEMUARCH
COPY --from=qemu /usr/bin/qemu-${QEMUARCH}-static /usr/bin/

COPY ./build_container_common.sh /
COPY ./build_container_ubuntu.sh /

RUN ./build_container_ubuntu.sh

# Remove qemu program
RUN rm -f /usr/bin/qemu-${QEMUARCH}-static
