parameters:
- name: bazeliskInstallCommandPrefix
  displayName: "Bazelisk Install Command Prefix"
  type: string
  default: "sudo"
- name: bazeliskInstallPath
  displayName: "Bazelisk Install Path"
  type: string
  default: "/usr/local/bin/bazel"
- name: bazeliskReleaseFilename
  displayName: "Bazelisk Relase Filename"
  type: string
  default: bazelisk-linux-amd64
- name: osFamily
  displayName: "OS Family"
  type: string
  default: "linux"
- name: gcrImageName
  displayName: "GCR Image Name"
  type: string
  default: "envoy-build"

steps:
- bash: |
    rm -rf /c/Windows/System32/bash.exe
  condition: eq(variables['Agent.OS'], 'Windows_NT')
- bash: |
    ${{  parameters.bazeliskInstallCommandPrefix  }} curl -sSL -o ${{  parameters.bazeliskInstallPath  }} https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/${{  parameters.bazeliskReleaseFilename  }}
    ${{  parameters.bazeliskInstallCommandPrefix  }} chmod +x ${{  parameters.bazeliskInstallPath  }}
  displayName: Install Bazelisk
- task: InstallSSHKey@0
  inputs:
    hostName: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
    sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCns5kFJ6w7c/zH/FYBNvSpqhpSL147fizsru+PYwaw36RMCkJ4wqHVqusq6zF6K8SPloA4AlzPWx50i2NhRj8NEKgg3IkO35uFciEBcTwqr5+o+e96CvryNwGDZfavgUfrMwTQBYWdM7aaBoWUk31zmUixtlalgBEC1JGdEFxYpN3AmqN50mbu9ZvV8IEv8/AInqvqkS+dIzE9EcZQZQ98uDRU99S1YDCcvZO6xidGZz42AbS8CJ6idrreBoqy/eXmgio4YjGGFRnqr1tdXG5GKWSxfcrSC/gE8OzpFTJ1WOWH+SdZCptev8er6MBoFgRNkDhRckzpsAjhIYxSIAaL"
    sshPassphrase: "$(SshKeyPassphrase)"
    sshKeySecureFile: id_rsa_envoy_ci
  condition: ne(variables['Build.Reason'], 'PullRequest')
- task: GoTool@0
  inputs:
    version: '1.16'
- bash: |
    toolchains/regenerate.sh
  env:
    COMMIT_TOOLCHAINS: "true"
    GCR_IMAGE_NAME: ${{  parameters.gcrImageName }}
    OS_FAMILY: ${{  parameters.osFamily  }}
    SOURCE_BRANCH: $(Build.SourceBranch)
  displayName: Generate toolchains
