name: Lint

on:
  pull_request:
    paths:
    - '**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run ShellCheck on all scripts
      run: |
        # Find all .sh files and run shellcheck
        # -f gcc makes the output clickable in GitHub UI
        shopt -s globstar nullglob
        shellcheck -f gcc **/*.sh
